excluded: # paths to ignore during linting. Takes precedence over `included`.
  - ${PODS_ROOT}
  - ${SOURCE_ROOT}/Tools
disabled_rules:
  - class_delegate_protocol
  - cyclomatic_complexity
  - file_length
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - identifier_name
  - is_disjoint
  - large_tuple
  - line_length # TODO: restore with a sensible maximum length
  - nesting
  - syntactic_sugar
  - trailing_comma
  - trailing_whitespace
  - type_body_length
  - type_name
  - unused_setter_value
  - private_over_fileprivate
  - implicit_getter
  - opening_brace
  
custom_rules:
  app_fatal_error:
    name: "FatalError"
    regex: "fatalError"
    message: "Please use `preconditionFailure` instead. (custom_rules: app_fatal_error)"
    severity: error
  swiftgen_assets:
    name: "SwiftGen Assets"
    regex: '(UIImage|UIColor)(\.init)?\(named: ?"?.+"?(, ?in:.+?, ?compatibleWith:.+?)?\)|#imageLiteral\(resourceName: ?".+"\)'
    message: "Use Asset.<asset> instead"
    severity: error
  swiftgen_colors:
    name: "SwiftGen Colors"
    regex: '(UIColor(\.init)?|#colorLiteral)\(((red|displayP3Red):.+?,green:.+?,blue:.+?,alpha:.+?)|(white:.+?,alpha:.+?)|(hue:.+?,saturation:.+?,brightness:.+?,alpha:.+?)\)'
    message: "Use ColorName.<color> instead"
    severity: error
  swiftgen_fonts:
    name: "SwiftGen Fonts"
    regex: 'UIFont(\.init)?\(name: ?"?.+"?, ?size:.+?\)'
    message: "Use FontFamily.<family>.<variant>.size(<size>) instead"
    severity: error
  swiftgen_storyboards:
    name: "SwiftGen Storyboard Scenes"
    regex: '(UIStoryboard\(name: ?"?.+"?, ?bundle:.+\))|(instantiateViewController\(withIdentifier:.+?\))|(instantiateInitialViewController\(\))'
    message: "Use StoryboardScene.<storyboad>.<scene>.instantiate() instead"
    severity: error
  swiftgen_strings:
    name: "SwiftGen Strings"
    regex: 'NSLocalizedString'
    message: "Use L10n.key instead"
    severity: error

opt_in_rules:
  - anyobject_protocol
  - array_init
  - closure_spacing
  - collection_alignment
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - flatmap_over_map_reduce
  - identical_operands
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_random
  - lower_acl_than_parent
  - modifier_order
  - no_extension_access_modifier
  - overridden_super_call
  - pattern_matching_keywords
  - prohibited_super_call
  - reduce_into
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - unused_declaration
  - unused_import
  - vertical_whitespace_closing_braces
  - yoda_condition

vertical_whitespace:
  max_empty_lines: 2
